name: API RPC Tests

on:
  schedule:
    # Run at midnight and midday UTC
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx pytest-asyncio  # Add other dependencies here

      # Step 4: Run pytest
      - name: Run API RPC Tests
        run: pytest api_rpc_tests/test_sample.py
